# python script to solve Project Euler Problem 2 (http://projecteuler.net/problem=2 )
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
num = 0
int1 = 1
int2 = 2
int3 = 0
# Skips checking int1 (1) for being an even number, as I know it is not.
while (int3 < 4000000):
  int3 = int1+int2
  int1 = int2
  int2 = int3
  if int1 % 2 == 0:
    num += int1
print('The answer is: %d' % num)
# Syntax error. Don't know why...